### PR TITLE
Resolved Bug 1368: Design System > Components > Password Setting > Default > The new password and confirm new password validation are not displayed properly. 

### LINKED ISSUE #1368: Design System > Components > Password Setting > Default > The new password and confirm new password validation are not displayed properly.
**Describe the bug**
1.The new password and confirm new password validation are not displayed properly.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/?path=/story/components-password-setting--default'
2. Navigate to 'Design System > Components > Password Setting > Default'
3. Enter random password. 

**Actual result-**
The new password and confirm new password validation are not displayed properly.

**Screenshots**
image

**Expected result-**
The new password and confirm new password validation should be displayed properly.
"New Password and Confirm New Password do not match. Please try again."

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by nknikhilkasar**
## Description

-**Fixed the logic for  new password and confirm new password field**

Screenshot 2025-01-07 223511

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx [hunk 1]
```diff
@@ -26,43 +29,35 @@ const RdsCompPasswordSetting = (props: RdsCompPasswordSettingProps) => {
...
-                    }
+                    !isNewPassValid(value) ? setNewPassError("Password must be alphanumeric and at least 8 characters long") : setNewPassError("");
                     break;
                 case "curNewPass":
-                    if (!isCurNewPassValid(value)) {
-                        setError3("Password mismatch found");
-                    } else {
-                        setError3("");
-                    }
+                    !isCurNewPassValid(value) ? setCurNewPassError("Password mismatch found") : setCurNewPassError("");
```
Comment (WAi-Aditya) [inline raaghu-components/src/rds-comp-password-setting/rds-comp-password-setting.tsx]: Error message should be as per describe in bug.

**Review by WAi-Aditya — CHANGES_REQUESTED** [review]

**Review by WAi-Aditya — APPROVED** [review]
