### PR TITLE
Resolved Bug 1344 : Design System > Components > Claims And Developer Mode > Default > Input box highlighted in required color

### LINKED ISSUE #1344: Design System > Components > Claims >Default > Input box highlighted in different color.
**Describe the bug**
 1. Claims >Default > Input box highlighted in different color.
 2. Developer Mode > Default > Application Grant Type - Input box highlighted in different color.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
3. Navigate to 'Design System > Components > Claims >Default'
4. Click on select claim type & click on Enter value input box.

**Actual result-**
 1. Claims >Default > Input box highlighted in different color.
 2. Developer Mode > Default > Application Grant Type - Input box highlighted in different color.

**Screenshots**
image
image

**Expected result-**
 1. Claims >Default > Input box highlighted in same color.
 2. Developer Mode > Default > Application Grant Type - Input box highlighted in same color.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by SoheshMG**
## Description

>Resolve issue Input box highlighted in different color > Components > Claims  > Default
>Resolve issue Input box highlighted in different color > Components > Developer Mode  > Default > Application Grant Type

-**Resolved all highlighted color issues by changing the select list**
-**Added color props in storybook to select list**
-**Resolved multi select issue in claims component**
-**Resolved highlighted color issues for Claims, Developer Mode and Claim Type**

## Screenshots
image
image
image
image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rohit9096 — APPROVED** [review]
Review and Approved

File: raaghu-elements/src/rds-select-list/rds-select-list.tsx [hunk 1]
```diff
@@ -100,7 +146,21 @@ const RdsSelectList = (props: RdsSelectProps) => {
...
  
     return (
-      <div id="select-background-color">
+      <div
+        id="select-background-color"
+        style={{
+          backgroundColor:
+            optionProps.isFocused || optionProps.isSelected
+              ? props.color === "primary"
+                ? "#b38de9"
```
Comment (WAi-Aditya) [inline raaghu-elements/src/rds-select-list/rds-select-list.tsx]: these should come from variable.

File: raaghu-elements/src/rds-select-list/rds-select-list.tsx [hunk 2]
```diff
@@ -100,7 +146,21 @@ const RdsSelectList = (props: RdsSelectProps) => {
...
+                : props.color === "danger"
+                ? "#ffd6d6"
```
Comment (WAi-Aditya) [inline raaghu-elements/src/rds-select-list/rds-select-list.tsx]: Hard coded values are not recommended.

**Review by WAi-Aditya — CHANGES_REQUESTED** [review]

**Comment by SoheshMG** [comment]
@WAi-Aditya Done necessary changes,
Please review the changes.

**Review by WAi-Aditya — APPROVED** [review]

File: raaghu-elements/src/rds-select-list/rds-select-list.tsx (hunk 1 above)
Comment (SoheshMG) [reply raaghu-elements/src/rds-select-list/rds-select-list.tsx]: Removed hard coded color values and added variables

File: raaghu-elements/src/rds-select-list/rds-select-list.tsx (hunk 2 above)
Comment (SoheshMG) [reply raaghu-elements/src/rds-select-list/rds-select-list.tsx]: Removed hard coded color values and added variables
