### PR TITLE
Resolved Bug 470 and 481 : Elements > Notification > Selecting dark theme button text is not display and Storybook > Elements > Card Detail > Selecting small mobile view radio button is stick on card text. 

### LINKED ISSUE #470: Elements >Notification> Selecting dark theme button text is not display.
**Describe the bug**
1. Notification> Default > Selecting dark theme button text is not display.
2. Size >With Description> Selecting dark theme card text is not display.
3. Widget Portal > Default >Selecting dark theme button text is not display.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Notification'
3. Click on 'Default'

**Screenshots**
image

image

image

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

### LINKED ISSUE #481: Storybook > Elements >Card Detail >Selecting small mobile view radio button is stick on card text.
**Describe the bug**
1. Selecting small mobile view radio button is stick on card text.
2. Elements> Avatar >With Initial >Selecting dark theme Initial latter is not display.
3. Elements> Avatar >With Label>Selecting dark theme label is not display proper.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Card Detail'
5. Click on 'Card Detail'

**Expected behavior**
Selecting small mobile view space between card text and radio button.
Selecting dark theme Initial latter is display like WT.
**Screenshots**
Card Detail -
image

Avatar -
image

Avatar >With Label -
image

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

### PR DESCRIPTION
**Pull request by pravinwaghmare23**
## Description
> Make the changes to rds-widget-portal.css, rds-size.css, rds-notification.css, rds-card-detail.tsx, rds-avatar.css
> Resolved Elements>Notification> Default > Selecting dark theme button text is not display.
> Resolved Elements>Size >With Description> Selecting dark theme card text is not display.
> Resolved Elements>Widget Portal > Default >Selecting dark theme button text is not display.
> Resolved Elements>Card Details > Card Details > Selecting small mobile view radio button is stick on card text.
> Resolved Elements>Avatar >With Initial >Selecting dark theme Initial latter is not display.
> Resloved Elements>Avatar >With Label>Selecting dark theme label is not display proper.

image

> Elements> Size >With Description
image

> Elements> Widget Portal > Default 
image

> Elements> Card Details > Card Details 
image

> Elements>Avatar >With Initial 
image

> Elements>Avatar >With Label
image

 

 

## Checklist:
 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New

### CODE REVIEW

File: raaghu-elements/src/rds-card-detail/rds-card-detail.tsx [hunk 1]
```diff
@@ -44,13 +44,15 @@ const RdsCardDetail = (props: RdsCardDetailProps) => {
                                                 colorVariant={data.iconColorVarient}
                                             />
 
-                                            <div className="ms-3  ">
-                                                <div className="ms-3 d-flex fs-6">
+                                            <div className="ms-1 text-nowrap">
```
Comment (suraj-khupse) [inline raaghu-elements/src/rds-card-detail/rds-card-detail.tsx]: no need no wrap

**Review by suraj-khupse — CHANGES_REQUESTED** [review]

File: raaghu-elements/src/rds-card-detail/rds-card-detail.tsx (hunk 1 above)
Comment (pravinwaghmare23) [reply raaghu-elements/src/rds-card-detail/rds-card-detail.tsx]: Resolved Comments

**Review by Ketan-Khalate — APPROVED** [review]

**Review by Ketan-Khalate — APPROVED** [review]

**Review by suraj-khupse — APPROVED** [review]
