### PR TITLE
 Resolved bug 1294: Elements> Grid > Enhancement as per Figma Design 

### LINKED ISSUE #1294: Design System > Component > Design changes in grid
Design System > Component > Design changes in grid
as per task https://github.com/Wai-Technologies/raaghu-portal/issues/1446 and bellow screen

Image

### PR DESCRIPTION
**Pull request by Dipak7028**
1. Completed Enhancement Review Elements per the figma kit.

## Screenshots:
image
image

 
 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx [hunk 1]
```diff
@@ -1,1897 +1,707 @@
...
+  }[];
+  tableData: any[];
+  pagination?: boolean;
+  isClickable?: boolean;
+  recordsPerPage?: number;
+  recordsPerPageSelectListOption?: boolean;
+  onActionSelection?: (rowData: any, actionId: any) => void;
+  onRowSelect?: (data: any) => void;
+  onRowClick?: (rowId: any) => void;
+  actionPosition?: "right" | "left";
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx]: use enum

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx [hunk 2]
```diff
@@ -1,1897 +1,707 @@
...
+  onPaginationHandler?: (currentPage: number, recordsPerPage: number) => void;
+  totalRecords?: any;
+  actionColumnStyle?: "show dots" | "show buttons directly";
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx]: use enum

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx [hunk 3]
```diff
@@ -1,1897 +1,707 @@
...
+          <div className="d-flex align-items-center mt-1 ps-1 px-4">
+          <RdsSelectList
+  color="primary"
+  id="story"
+  isMultiple
+  isSearchable
+  label=""
+  onChange={function Xs(){}}
+  placeholder="filter....."
+  selectItems={[
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx]: create one array and then call that here

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx [hunk 4]
```diff
@@ -2914,6 +1742,13 @@ const RdsCompGrid = (props: RdsCompGridCombinedProps) => {
                     })}
                 </tbody>
               </table>
+              <div className="ps-3 ms-1">
+                <RdsIcon
+                  colorVariant="dark"
+                  isCursorPointer
+                  name="pluss"
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx]: use proper naming convention

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx [hunk 5]
```diff
@@ -2938,3 +1773,1357 @@ const RdsCompGrid = (props: RdsCompGridCombinedProps) => {
...
+//                             ))}
+//                           </ul>
+//                         </div>
+//                       </>
+//                     </td>
+//                   )}
+//               </DraggableRow>
+//             ))}
+//           </tbody>
+//           </table>
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx:3108]: If commented code is not for future reference remove it

**Comment by Dipak7028** [comment]
icon name changes

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx (hunk 4 above)
Comment (Dipak7028) [reply raaghu-components/src/rds-comp-grid/rds-comp-grid.tsx]: icon name  change

**Comment by Dipak7028** [comment]
@rameshwarkamandar please check this comment .

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.css [hunk 6]
```diff
@@ -63,7 +63,25 @@
 }
 
 .badge-primary {
-  background-color: #d4bbff;
-  color: #7825e9;
   margin-left: 8px;
+}
+.btn.btn-transparent-primary {
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.css]: apply Id specific Css

File: raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx [hunk 7]
```diff
@@ -1,5 +1,5 @@
 import type { Meta, StoryObj } from '@storybook/react';
-import RdsCompGrid from "./rds-comp-grid";
+import RdsCompGrid, {  } from "./rds-comp-grid";
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-grid/rds-comp-grid.stories.tsx]: remove unwanted brackets

File: raaghu-elements/src/rds-select-list/rds-select-list.css [hunk 8]
```diff
@@ -70,4 +70,7 @@
 }
 .css-ebdihx-option:active{
     background-color: white !important;
+}
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-select-list/rds-select-list.css:73]: apply id or class specific css

**Review by supriyartambewaiin — APPROVED** [review]
Approved
