### PR TITLE
Resolved Bug 1785: Design System > Components > File Management Tree > Icons disappear in dark theme

### LINKED ISSUE #1785: Design System > Components > File Management Tree > Icons disappear in dark theme
**Describe a Bug**
Icons disappear in dark theme

**Steps to Reproduce a Bug**
1. Login to https://stage-react.raaghu.ai/?path=/story/components-file-management-tree--default&globals=theme:dark
2. Navigate Components > File Management Tree
3. Checks icons

**Actual Result**
Image

**Expected Result**
Icons should be appear

### PR DESCRIPTION
**Pull request by Sachin-Ghorpade**
## Screenshots :
 
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by supriyartambewaiin — COMMENTED** [review]
Don't change icons strokes directly. maybe it uses somewhere else

**Comment by supriyartambewaiin** [comment]
image
not working for small and large view

**Comment by Dipak7028** [comment]
### **_fix on Small and Large view_**
image
image

**Comment by supriyartambewaiin** [comment]
image
 check ui proper

File: raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx [hunk 1]
```diff
@@ -169,7 +169,7 @@ export const RdsCompFileManagementTree = (props: RdsCompFileManagementTreeProps)
     };
 
 
-    return <ul className="pt-1 cursor-pointer pb-3">{renderDirectoryItems(props.items)}</ul>;
+    return <ul className="pt-1 cursor-pointer pb-3 p-4">{renderDirectoryItems(props.items)}</ul>;
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-fileManagement-Tree/rds-comp-fileManagement-Tree.tsx]: don't remove this. this is impacting on alignment of hover dropdown

**Review by supriyartambewaiin — APPROVED** [review]
Approved
