### PR TITLE
added pagination, made admin dashboard responsive, fixed table header

### LINKED ISSUE #591: Add todo list table on dashboard page for 4k view

### PR DESCRIPTION
**Pull request by Vikrantsingh441**
## Description

[added pagination, made admin dashboard responsive, fixed table header

Fixes #591 #604 #586 

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-table/rds-table.tsx [hunk 1]
```diff
@@ -12,76 +13,90 @@ export interface RdsTableProps {
...
+          </tr>
+        </thead>
+        <tbody>
+          {props.tableDatas.map((tableData) => (
+            <>
+              <tr className="normal-rows">
+                {props.headerDatas.map((headerData) => (
+                  <>
+                    {headerData.dataType == "text" ? (
+                      <td className="align-middle" width="40%">
```
Comment (amarphule) [inline raaghu-elements/src/rds-table/rds-table.tsx:63]: key props is missing in map()

**Review by amarphule — APPROVED** [review]
looks good for now, please add key prop to map()'s parent div

**Review by amarphule — COMMENTED** [review]
looks good for now, please add key prop to map()'s parent div

**Review by amarphule — APPROVED** [review]
Reviewed changes and approved
