### PR TITLE
Bug 1508: Resolved Issue Design System > Component > Contribution > Enhancement as per Figma Design.

### LINKED ISSUE #1508: Design System > Component > Contribution > Enhancement as per Figma Design
Design System > Component > Contribution > Enhancement as per Figma Design

### PR DESCRIPTION
**Pull request by rameshwarkamandar**
## Screenshots :
image
image
image
image
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx [hunk 1]
```diff
@@ -163,7 +163,7 @@ export const RdsCompContribution = (props: RdsCompContributionProps) => {
   return (
     <Measure bounds onResize={ (rect) => updateSize(rect.bounds) }>
       { ({ measureRef }: any) => (
-        <div ref={ measureRef } className="full-width">
+        <div ref={ measureRef } >
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-contribution/rds-comp-contribution.tsx]: Don't remove classes. and check responsiveness

**Comment by supriyartambewaiin** [comment]
Not working as expected check mobile view

**Comment by supriyartambewaiin** [comment]
image
not working

**Review by supriyartambewaiin — APPROVED** [review]
Approved
