### PR TITLE
Resolved Bug 828: Design System > App Shell > Add new app shell as per figma design

### LINKED ISSUE #828: Design System > App Shell > Add new app shell as per figma design
Design System > App Shell > Add new app shell as per figma design
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=2799-7847&node-type=frame&t=u9Y9G2nAqmIsPYV3-0

### PR DESCRIPTION
**Pull request by rushigadekarWai**
-  **Top nav**
- **Relaxing**
1.fix the issue of hand cursor missing 
2.Fix the issue of Alignment and spacing still not proper
Language abbreviation and arrow still not properly aligned

## Screenshots :
1. 
image

2. 
image

 
 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx [hunk 1]
```diff
@@ -138,6 +138,12 @@ const RdsBreadcrumb = (props: BreadcrumbProps) => {
                 : { borderBottom: `2px solid ${props.borderColor}` })
             : {};
 
+          // Add cursor pointer for level 5 items or when there are multiple items in array
+          const shouldShowCursor = props.level === 'Level 5' || props.breadcrumbItems.length > 1;
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx]: just showing hand cursor this much code is required??

Comment (rushigadekarWai) [reply raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx]: resolved

Comment (rushigadekarWai) [reply raaghu-elements/src/rds-breadcrumb/rds-breadcrumb.tsx]: Resolve

**Review by supriyartambewaiin — APPROVED** [review]
