### PR TITLE
Resolved bug 1548: Design System > Elements > Side navigation > Custom Navigation Side bar right > UI issues in Side Navigation. 

### LINKED ISSUE #1548: Design System > Elements > Side navigation > Custom Navigation Side bar right > UI issues in side navigation
**Describe the bug**
1.Not able to see side navigation
2. Excess side nav is displayed in tablet view

**Steps to reproduce bug**
1. Login with 'https://react.raaghu.ai/?path=/story/elements-side-navigation--custom-navigation-sidebar-with-list&globals=theme:dark'
2. Navigate to "Elements > Side navigation > Custom Navigation Side bar right "

**Actual result-**
1.Not able to see side navigation
2. Excess side nav is displayed in tablet view

**Screenshots**

Image

Image

Image

**Expected result-**
 1.Side navigation should show
2. Excess side nav should not displayed in tablet view

### PR DESCRIPTION
**Pull request by Dipak7028**
## Screenshots:
image
image
image
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-side-nav/rds-side-nav.tsx [hunk 1]
```diff
@@ -333,7 +333,7 @@ const RdsSideNav = (props: RdsSideNavProps) => {
                 <nav
                     id="sidebar"
                     ref={ref}
-                    className={`bd-links text-capitalize sidebar overflow-x-hidden overflow-y-auto pt-xxl-0 pt-xl-0 pt-lg-0 pt-md-0 pt-4 shadow px-1 side-navigation
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-side-nav/rds-side-nav.tsx]: don't remove classes directly check its dependency

**Comment by supriyartambewaiin** [comment]
image
Icons is not visible in dark mode

**Comment by supriyartambewaiin** [comment]
name is not visible

**Comment by supriyartambewaiin** [comment]
image
still it is not proper

**Review by nitinsonawane123 — APPROVED** [review]
Approved
