### PR TITLE
Resolved Bug 1148: Components Webhook Subscription Default Text alignment issue

### LINKED ISSUE #1148: Design System > Components > Webhook Subscription > Default > Text alignment issue.
**Describe the bug**
1. Webhook Subscription > Default > Text alignment issue.
2. User Table > Default > Small view Popup is hide.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Webhook Subscription > Default'

**Actual result-**
1. Webhook Subscription > Default > Text alignment issue.
2. User Table > Default > Small view Popup is hide.

**Screenshots**
image
image

**Expected result-**
1. Webhook Subscription > Default > Text alignment should be proper.
2. User Table > Default > Small view Popup should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by Sachin-Ghorpade**
-  **Resolved Text alignment issue**
-  **Resolved Small view Popup is hide**

## Screenshots :
image
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx [hunk 1]
```diff
@@ -189,7 +185,7 @@ const RdsCompWebhookSubscription = (props: RdsCompWebhookSubscriptionProps) => {
                                 dataTestId="header-value"
                             ></RdsInput>
                         </div>
-                        <div className="col-12 col-md-2 mb-3 mt-1 d-flex justify-content-center justify-content-md-end">
```
Comment (WAi-Aditya) [inline raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx:192]: We should not change this code, 
Alignment is getting disturb because of the same.

image

**Review by WAi-Aditya — CHANGES_REQUESTED** [review]

File: raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx (hunk 1 above)
Comment (Sachin-Ghorpade) [reply raaghu-components/src/rds-comp-webhook-subscriptions/rds-comp-webhook-subscriptions.tsx:192]: This Issue is resolved.

**Review by WAi-Aditya — APPROVED** [review]
