### PR TITLE
Resolved Bug 152 : User Role Rendering Issue

### LINKED ISSUE #152: Bug : Components > User Role Rendering Issue

### PR DESCRIPTION
**Pull request by supriyartambewaiin**
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Screenshots :

image

image

### CODE REVIEW

File: raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import React, { FC, useEffect, useState } from "react";
 import { RdsButton, RdsCheckbox, RdsLabel } from "../rds-elements";
 import { useTranslation } from "react-i18next";
-interface RdsCompUserRolesProps {
+export interface RdsCompUserRolesProps {
```
Comment (suraj-khupse) [inline raaghu-components/src/rds-comp-user-roles/rds-comp-user-roles.tsx]: please remove export before the interface

**Review by suraj-khupse — APPROVED** [review]

**Review by suraj-khupse — APPROVED** [review]
