### PR TITLE
Resolved bug 1276: Design System > Component > Webhook Subscription >Required message and alignment issue

### LINKED ISSUE #1276: Design System > Components > Webhook Subscription >Default > Required message and alignment issue.
**Describe the bug**
 Required message and alignment issue.

**Steps to reproduce bug**
1. Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Webhook Subscription >Default'

**Actual result-**
 Required message and alignment issue.

**Screenshots**
image

**Expected result-**
 Required message and alignment should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

### PR DESCRIPTION
**Pull request by Sachin-Ghorpade**
- Removed the **input-group** class from the **Rds-inpu**t component, as this CSS class was not needed. Verified all elements and components, and confirmed that removing this class does not affect anything.

## Screenshots :
 
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-input/rds-input.tsx [hunk 1]
```diff
@@ -257,7 +257,7 @@ const RdsInput = React.forwardRef<HTMLInputElement, RdsInputProps>(
         )}
     </label>
 )}
-          <div className="mb-0 input-group">
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-input/rds-input.tsx:260]: don't remove any classes directly

Comment (Sachin-Ghorpade) [reply raaghu-elements/src/rds-input/rds-input.tsx:260]: Removed the input-group class from the Rds-input component, as this CSS class was not needed there and i have Verified all elements and components, and confirmed that removing this class does not affect anything.

**Review by supriyartambewaiin — APPROVED** [review]
Approved
