### PR TITLE
Bug 1701: Resolved Issue on Hover effect is not applied sidebar icons.

### LINKED ISSUE #1701: Design System > Component > Create new component Side Bar as per design [Chat]
Design System > Component > Create new component Side Bar as per design [Chat]

### PR DESCRIPTION
**Pull request by rameshwarkamandar**
## Screenshots:
image

image

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-side-bar/rds-side-bar.tsx [hunk 1]
```diff
@@ -197,45 +217,83 @@ const RdsSidebar = (props: RdsSidebarProps) => {
...
-                <div key={index} className="dashboard">
-                  {renderNavButton(item)}
-                </div>
-              ))}
-            </div>
-          ))}
+ 
+          {/* Middle section with scrollbar */}
+          <div className="middle-section-container px-2"
+  style={{
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-side-bar/rds-side-bar.tsx]: remove inline style

File: raaghu-elements/src/rds-side-bar/rds-side-bar.tsx [hunk 2]
```diff
@@ -197,45 +217,83 @@ const RdsSidebar = (props: RdsSidebarProps) => {
...
+    overflowY: middleGroups.length > 0 ? "auto" : "hidden", 
+    maxHeight: "calc(100vh - 200px)", 
+  }}
+>
+ 
+  <div>
+    {middleGroups.map((group, groupIndex) => (
+      <div  style={{
+        overflowY: middleGroups.length > 0 ? "auto" : "hidden",
```
Comment (supriyartambewaiin) [inline raaghu-elements/src/rds-side-bar/rds-side-bar.tsx]: this one also

**Review by supriyartambewaiin — APPROVED** [review]
Approved
