### PR TITLE
Enhanced side nav and fixed top nav, and added Icon list to icons.tsx file.

### LINKED ISSUE #81: Create side navigation element.

### PR DESCRIPTION
**Pull request by agaurav0019**
## Description

Enhanced side nav and fixed top nav, and added Icon list to icons.tsx file.

Fixes #81 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-elements/src/rds-side-nav/rds-side-nav.tsx [hunk 1]
```diff
@@ -1,36 +1,42 @@
-import React from 'react'
-import "./rds-side-nav-new.scss"
-import RdsSideNavChild from './rds-side-nav-child'
+import React from "react";
+import "./rds-side-nav-new.scss";
+import RdsSideNavChild from "./rds-side-nav-child";
 import RdsIcon from "../rds-icon/rds-icon";
-import DarkMode from './DarkMode';
+import DarkMode from "./DarkMode";
```
Comment (amarphule) [inline raaghu-elements/src/rds-side-nav/rds-side-nav.tsx:5]: what is this dark mode component

File: raaghu-mfe/rds_pages/host/src/Main.tsx [hunk 2]
```diff
@@ -6,161 +6,148 @@ import { useSelector } from "react-redux";
...
+  RdsCompTopNavigation,
 } from "../../rds-components";
 const DashboardCompo = React.lazy(() => import("Dashboard/Dashboard"));
 const LoginCompo = React.lazy(() => import("Login/Login"));
 const ForgotPasswordCompo = React.lazy(
-	() => import("ForgotPassword/ForgotPassword")
+  () => import("ForgotPassword/ForgotPassword")
 );
 // const MaintainanceCompo = React.lazy(() => import("Maintainance/Maintainance"));
 // const TenantCompo = React.lazy(() => import("rds-page-tenant/Tenant"));
```
Comment (amarphule) [inline raaghu-mfe/rds_pages/host/src/Main.tsx:18]: remove comments

File: raaghu-mfe/rds_pages/host/src/Main.tsx [hunk 3]
```diff
@@ -6,161 +6,148 @@ import { useSelector } from "react-redux";
...
-			navigate("/dashboard");
-		}
-	}, [accessToken]);
+    console.log("this is access token", typeof accessToken);
+    // setIsAuth(true);
+    console.log(isAuth);
+    if (accessToken) {
+      setIsAuth(true);
+      console.log(accessToken);
+      navigate("/dashboard");
```
Comment (amarphule) [inline raaghu-mfe/rds_pages/host/src/Main.tsx:38]: remove comments, instead of var use let

**Review by amarphule — CHANGES_REQUESTED** [review]
added few suggestion please go through that
1. use `let` instead `var` key word
2. remove comments
3. remove console log

**Review by amarphule — APPROVED** [review]
reviewed changes and approved
