### PR TITLE
Resolved Bug :1763 Design System Component Cache Long Cache text are hidden behind delete button in mobile views

### LINKED ISSUE #1763: Design System > Components > Cache > Long Cache text are hidden behind delete button in mobile views
**Describe a Bug**
Long Cache text are hidden behind delete button in mobile views

**Steps to Reproduce a Bug**
1.Login to https://stage-react.raaghu.ai/?path=/story/components-cache--default&globals=viewport:mobile2
2.Navigate > Components >
3.Notice how the text overlaps

**Actual Result**
Image

Image

**Expected Result**
The cache text should be fully visible and not overlap with the delete button

### PR DESCRIPTION
**Pull request by Dipak7028**
-**Text should in small mobile fix**

## Screenshots :
image
image

 
## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx [hunk 1]
```diff
@@ -100,7 +100,7 @@ const RdsCompCache = (props: RdsCacheProps) => {
                             <div className="icon">
                                 <button
                                     type="button"
-                                    className="btn btn-primary fixed-button"
+                                    className="btn btn-primary "
```
Comment (supriyartambewaiin) [inline raaghu-components/src/rds-comp-cache/rds-comp-cache.tsx]: don't remove this property, use media query for responsiveness or else use bootstrap classes

**Review by supriyartambewaiin — APPROVED** [review]
Approved
